name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Environment Variables
        run: echo "MONGODB_URL=${{ secrets.TWITER_API_NESTJS_PRODUCTION_MONGODB_URL }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start Nest.js App
        run: npm start
