name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false

        

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Start Nest.js App
      run: npm start
