name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.TWITTER_MONGODB_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create .env
        run: echo "MONGODB_URL=${MONGODB_URL}" >> .env

      - name: Display .env
        run: cat .env

      - name: Start Nest.js App
        run: npm start
