name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Log MongoDB connection info
        run: echo "MongoDB connection: ${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@cluster0.q4ixk31.mongodb.net/twiter"

      - name: 'Create env file'
        run: |
          echo "MONGODB_URL=mongodb+srv://${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@cluster0.q4ixk31.mongodb.net/twiter" > .env

      - name: Build
        run: npm run build

      - name: Start Nest.js App
        run: npm start
