name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: 'Set up env variables'
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV

      - name: 'Create env file'
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env

      - name: 'Write env file'
        run: cat .env

      - name: Build
        run: npm run build

      - name: Start Nest.js App
        run: npm start
